### ISSUE TITLE
opacities.db vs. opacity.db

### ISSUE THREAD

**Issue by jkteske** [natashabatalha/picaso#124]
In this new CHIMERA-less version of the tutorial, the set-up at the top does not explicitly say where to put the opacity.db file. It should go in ../picaso_reference/opacities. Also, I think the file needs to be named "opacity.db", not "opacities.db"; the latter is the name of the file downloaded from Zenodo (https://zenodo.org/record/3759675#.Y7XMby-B2EB). Without renaming the file, I get the following error:

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-24-476e681657ae> in <module>
      1 #load opacities
----> 2 opas = pj.opannection(wave_range=[1,12]) #defined in code 1
      3 
      4 #load planet in the same way as before
      5 gj436_trans = pj.load_planet(choose_from.loc[choose_from['pl_name']==planet_name],

~/.conda/envs/propexo/lib/python3.7/site-packages/picaso/justdoit.py in opannection(wave_range, filename_db, raman_db, resample)
    364         filename_db = os.path.join(__refdata__, 'opacities', inputs['opacities']['files']['opacity'])
    365         if not os.path.isfile(filename_db):
--> 366             raise Exception('The opacity file does not exist: '  + filename_db+' The default is to a file opacities.db in reference/opacity/. If you have an older version of PICASO your file might be called opacity.db. Consider just adding the correct path to filename_db=')
    367     elif not isinstance(filename_db,type(None) ):
    368         if not os.path.isfile(filename_db):

Exception: The opacity file does not exist: /Users/jteske/Documents/staff/research/observing_proposals/propexo/picaso_reference/opacities/opacity.db The default is to a file opacities.db in reference/opacity/. If you have an older version of PICASO your file might be called opacity.db. Consider just adding the correct path to filename_db=

**Comment by natashabatalha** [comment]
Just to follow through: 

Issue: This problem is encountered when an outdated version of the code is installed with up to date reference data (in this case picaso 2.0.2). As the error message indicates, the file should be called opacities.db, not opacity.db.

Fix: Ensure picaso is up to date (3.0+) 

Other notes: 
- this issue was caused by installing picaso via the now archived `propexo` [Github:](https://github.com/natashabatalha/propexo ) . Users wishing to follow the Sagan School 2020 tutorial should [use this tutorial](https://natashabatalha.github.io/picaso/workshops.html#sagan-school-2020-writing-a-jwst-proposal) instead

**Comment by jkteske** [comment]
Also, various other packages will also need to be updated with the picaso update, e.g., bokeh, pandas.
