### ISSUE TITLE
find_nearest takes first value if there are duplicates

### ISSUE THREAD

**Issue by lcmayor** [natashabatalha/picaso#4]
if the cumulative opacities in photo_attenuation are 0 until a certain level find_nearest picks the first when it should be taking the last.

suggest changing find_nearest to np.where functionality numpy.where(x == x.min()) and take [-1]

**Comment by natashabatalha** [comment]
Fixed in `dev` with addition of two functions [find_nearest_2d](https://github.com/natashabatalha/picaso/blob/3089fa1cff43ecfd2cfb2ac21a7987408c87a0e3/picaso/justplotit.py#L657) and [find_nearest_1d](https://github.com/natashabatalha/picaso/blob/3089fa1cff43ecfd2cfb2ac21a7987408c87a0e3/picaso/justplotit.py#L670).
